### ISSUE TITLE
feat: 빈 home screen 생성

### ISSUE THREAD

**Issue by ShinYoung-Kim** [ShinYoung-Kim/Attention#1]
### Todo
- [x] 폴더 위치 변경
- [x] Home screen 생성
- [x] empty home template 생성
- [ ] day js 설치 및 현재 날짜 표시
- [x] pretendard 폰트 연결
